version: "3.9"

services:
  database:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  fetcher:
    build: ./fetcher
    container_name: yahoo-finance-app
    depends_on:
      - database 
    volumes:
      - ./tickers.json:/app/tickers.json
      - ./fetcher:/app
    working_dir: /app
    command: ["/bin/sh", "run.sh"]

volumes:
  pgdata:
