version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  fetcher:
    build: ./fetcher
    container_name: yahoo-finance-app
    depends_on:
      - db
    volumes:
      - ./tickers.json:/app/tickers.json
    command: ["/bin/sh", "-c", "while true; do python main.py; sleep 14400; done"]

volumes:
  pgdata: