services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/example

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=example_user
      - POSTGRES_PASSWORD=example_password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: